### ISSUE TITLE
cannot refresh status

### ISSUE THREAD

**Issue by mentaluproar** [joeshaw/carwings-homecontrol#1]
When I start up the task, I get the error "Error getting climate control status: climate status not available" and "Battery info update complete: 0%, not charging"

**Comment by joeshaw** [comment]
Could you try the command-line tool from https://github.com/joeshaw/carwings and let me know what it says there?

Also, what region are you in, and what model year is your Leaf?

**Comment by mentaluproar** [comment]
The command line tool works great.  North America, 2013 leaf.  Already had the 2G radio replaced with 3G.

**Comment by joeshaw** [comment]
The climate control status error happens when the car has nothing to report.  I am not sure what causes the API do fail to return any climate info.  That's "working."

The battery info I believe is an issue with how older Leaf's report their charge through Carwings.  When it's merged, this commit should fix that: https://github.com/joeshaw/carwings/pull/7/commits/97a81e766ca6bd248beb72112d72491f499f0368

**Comment by mentaluproar** [comment]
Since then I’ve removed the accessory from my phone but I can’t add it back. Should I just not bother until the merge? As is, literally nothing works with the HomeKit code.

**Comment by joeshaw** [comment]
You should see no difference in behavior between the carwings command-line tool and the homecontrol service.  I'd expect you to see 0% battery on the CLI as well.

But yes, I would suggest waiting until after the merge happens.

Any logging you can attach from carwings-homecontrol would also be helpful.

**Comment by mentaluproar** [comment]
Where are the logs stored?
Is it possible the homecontrol version is still using the old Carwings URL?
How often does this poll Nissan for things like battery level or charging status?

**Comment by joeshaw** [comment]
The logs are written to standard error.

The homecontrol version just uses the carwings library under the covers (as does the CLI) so they should be using the same URL.  If you installed with `go get`, you can use `go get -u` to ensure you have the latest version of all the dependencies.  Since I developed the carwings library for the homecontrol program, they're pretty much in lockstep and I haven't felt the need to vendor the library with the homecontrol program.

It currently polls every 15m +/- 2m of jitter.  It also polls initially at startup before exposing itself as an accessory, to ensure it has valid data initially.

**Comment by mentaluproar** [comment]
Forgive my ignorance but where is standard error on Debian?

Feature request: reduce the frequency of queries if the vehicle is not plugged in. This reduces unneeded network traffic and can protect leafs with 12v batteries that aren’t in the best of shape. (The 3G TCM upgrades used in the US have a glitch were the radios don’t always go to sleep and frequent polling could risk keeping one awake overnight. I’m getting mine reflashed on Friday but many others just don’t get the fix.) We really only care about being that up to date while it is actually charging.

**Comment by joeshaw** [comment]
Standard error is usually printed out on the console.  If you're running it by hand, it should just be printed out for you.  If you're running it with systemd, you should be able to see if with `journalctl`.

Good suggestion on the reduced checkin when not plugged in.  Of course, we have to query to see if the vehicle is plugged in, but once we see that it isn't we can back off a bit to, say, once an hour.  I'll look into this and into making it configurable.

**Comment by mentaluproar** [comment]
I think I broke something with go:

```
sean@rock64:~$ go get -u
package _/srv/dev-disk-by-id-dm-name-vgWDreds-lvWDreds/homes/sean: unrecognized import path "_/srv/dev-disk-by-id-dm-name-vgWDreds-lvWDreds/homes/sean" (import path does not begin with hostname)
sean@rock64:~$ cd ~
sean@rock64:~$ cd gocode
sean@rock64:~/gocode$ go get -u
package _/srv/dev-disk-by-id-dm-name-vgWDreds-lvWDreds/homes/sean/gocode: unrecognized import path "_/srv/dev-disk-by-id-dm-name-vgWDreds-lvWDreds/homes/sean/gocode" (import path does not begin with hostname)
sean@rock64:~/gocode$ go get carwings-homecontrol -u
package carwings-homecontrol: unrecognized import path "carwings-homecontrol" (import path does not begin with hostname)
package -u: unrecognized import path "-u" (import path does not begin with hostname)
sean@rock64:~/gocode$ go get -u carwings-homecontrol
package carwings-homecontrol: unrecognized import path "carwings-homecontrol" (import path does not begin with hostname)
sean@rock64:~/gocode$ go get -u all
src/golang.org/x/text/cmd/gotext/main.go:31:2: cannot find package "golang.org/x/tools/go/buildutil" in any of:
	/usr/local/go/src/golang.org/x/tools/go/buildutil (from $GOROOT)
	/srv/dev-disk-by-id-dm-name-vgWDreds-lvWDreds/homes/sean/gocode/src/golang.org/x/tools/go/buildutil (from $GOPATH)
src/golang.org/x/text/message/pipeline/extract.go:21:2: cannot find package "golang.org/x/tools/go/callgraph" in any of:
	/usr/local/go/src/golang.org/x/tools/go/callgraph (from $GOROOT)
	/srv/dev-disk-by-id-dm-name-vgWDreds-lvWDreds/homes/sean/gocode/src/golang.org/x/tools/go/callgraph (from $GOPATH)
src/golang.org/x/text/message/pipeline/extract.go:22:2: cannot find package "golang.org/x/tools/go/callgraph/cha" in any of:
	/usr/local/go/src/golang.org/x/tools/go/callgraph/cha (from $GOROOT)
	/srv/dev-disk-by-id-dm-name-vgWDreds-lvWDreds/homes/sean/gocode/src/golang.org/x/tools/go/callgraph/cha (from $GOPATH)
src/golang.org/x/text/message/pipeline/extract.go:23:2: cannot find package "golang.org/x/tools/go/loader" in any of:
	/usr/local/go/src/golang.org/x/tools/go/loader (from $GOROOT)
	/srv/dev-disk-by-id-dm-name-vgWDreds-lvWDreds/homes/sean/gocode/src/golang.org/x/tools/go/loader (from $GOPATH)
src/golang.org/x/text/message/pipeline/extract.go:24:2: cannot find package "golang.org/x/tools/go/ssa" in any of:
	/usr/local/go/src/golang.org/x/tools/go/ssa (from $GOROOT)
	/srv/dev-disk-by-id-dm-name-vgWDreds-lvWDreds/homes/sean/gocode/src/golang.org/x/tools/go/ssa (from $GOPATH)
src/golang.org/x/text/message/pipeline/extract.go:25:2: cannot find package "golang.org/x/tools/go/ssa/ssautil" in any of:
	/usr/local/go/src/golang.org/x/tools/go/ssa/ssautil (from $GOROOT)
	/srv/dev-disk-by-id-dm-name-vgWDreds-lvWDreds/homes/sean/gocode/src/golang.org/x/tools/go/ssa/ssautil (from $GOPATH)
sean@rock64:~/gocode$ 
```

**Comment by joeshaw** [comment]
Try `go get -u github.com/joeshaw/carwings-homecontrol`

(packages in Go are specified by their import path, which is mostly a URL)

**Comment by mentaluproar** [comment]
sean@rock64:~$ carwings-homecontrol -config cwgoconfig.json 
2018/09/06 19:46:01 Connecting to Carwings service
2018/09/06 19:46:10 Connected to Carwings
2018/09/06 19:46:10 Entering battery update loop
2018/09/06 19:46:10 Entering climate control update loop
2018/09/06 19:46:10 Updating battery information
2018/09/06 19:46:10 Updating climate control information
2018/09/06 19:46:12 Error getting climate control status: climate status not available

It doesn't progress from there.

**Comment by joeshaw** [comment]
Battery status should be fixed now, so I'm going to close this.  Thanks for the report.

(Note it looks like Nissan has changed their API and some other things have broken, but I am working on those.)

**Comment by joeshaw** [comment]
joeshaw/carwings@472119c9 and joeshaw/carwings@983e416376aa39158dc0118c4d05528d1d4b07e4 are the fixes in the https://github.com/joeshaw/carwings module.
